### ISSUE TITLE
Cannot install extension from Chrome Web Store

### ISSUE THREAD

**Issue by SmellyCharlie** [InanZen/OverlayRemoverAuto#1]
It is currently not possible to install the extension from the Chrome Web Store.

![image](https://user-images.githubusercontent.com/46618792/59921452-f9fc2000-942d-11e9-9046-72e306414cae.png)

This seems to be a known issue https://bugs.chromium.org/p/chromium/issues/detail?id=29683

Error is not received when installing an unpacked extension locally - it installs just with a broken image in chrome://extensions 

![image](https://user-images.githubusercontent.com/46618792/59921640-aa6a2400-942e-11e9-82f1-ba6a8bb064ce.png)

**Comment by InanZen** [comment]
Strange bug, since svg icon works fine if extension is loaded in development mode.
EDIT: but you're saying yours doesn't even work in development mode?
