### ISSUE TITLE
Cannot Scroll Webpage after Overlay Removed

### ISSUE THREAD

**Issue by accretor** [InanZen/OverlayRemoverAuto#3]
Overlay Remover Auto successfully removed the ad block overlay on https://www.dailymail.co.uk/news/article-8244521/Wagga-Wagga-OVERTURNS-decision-cut-sister-city-ties-Kunming-coronavirus.html but afterwards, I can't scroll the page.

**Comment by InanZen** [comment]
I'm not seeing any overlays on the linked page.
Sometimes the detection algorithm removes the wrong part of the page. Checking the "stop timer if overlay found" might help. Or if there is no overlays on that page just disable it for that page (if you're using default enabled option).
